name:  $(GitVersion.NuGetVersion)

resources:
- repo: self
  fetchDepth: 30

pool:
  name: DCT
  demands:
  - IsBuildServer

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  inputs:
    updateAssemblyInfo: true
    preferBundledVersion: false
  displayName: GitVersion

- task: DotNetCoreInstaller@2
  inputs:
    version: 2.2.207
  displayName: 'Use .NET Core sdk 2.2.7 (VS2019 = 2.2.207)'



# Generate the report using ReportGenerator (https://github.com/danielpalme/ReportGenerator)
# First install the tool on the machine, then run it
- script: |
        dotnet tool install dotnet-reportgenerator-globaltool --version 4.3.6  
  displayName: Install dotnet-reportgenerator-globaltool
  continueOnError: true  
  enabled: false

- task: DotNetCoreCLI@2
  displayName: 'Restore Nuget packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: 'dct-pkg'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/ESFA.DC.SubmitLearnerData.API.Public.Service.Tests.csproj'
    feedsToUse: 'select'
    vstsFeed: 'dct-pkg'
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    configuration: $(BuildConfiguration) 
    arguments: '--no-restore -p:version="$(GitVersion.AssemblySemVer)" -p:FileVersion="$(GitVersion.AssemblySemFileVer)"'

# Run all tests with "/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura" to generate the code coverage file
- task: DotNetCoreCLI@2
  displayName: Run unit tests
  inputs:
    command: test
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    nobuild: true
    projects: '**/*Tests.csproj'

## Generate the report using ReportGenerator (https://github.com/danielpalme/ReportGenerator)
# First install the tool on the machine, then run it
- script: |
    dotnet tool install -g dotnet-reportgenerator-globaltool --version 4.3.6  
    reportgenerator -reports:$(Build.SourcesDirectory)/**/*Tests/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:Cobertura
  displayName: Create Code coverage report
  
# Publish the code coverage result (summary and web site)
# The summary allows to view the coverage percentage in the summary tab
# The web site allows to view which lines are covered directly in Azure Pipeline
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'

- task: DotNetCoreCLI@2
  displayName: 'Package Api Artifact Folder'
  inputs:
    command: publish
    configuration: $(BuildConfiguration) 
    publishWebProjects: false
    zipAfterPublish: true
    nobuild: true
    projects: '**/ESFA.DC.SubmitLearnerData.API.Public.csproj'
    arguments: '--output "$(build.artifactstagingdirectory)\Web\API"  -p:version="$(Build.BuildNumber)" -p:FileVersion="$(Build.BuildNumber)"'
    vstsFeed: 'dct-pkg'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Web'
  enabled: true
  inputs:
    ArtifactName: Web
    PathtoPublish: '$(build.artifactstagingdirectory)\Web'